# Generated by Django 4.2.18 on 2025-02-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='avatars/'),
        ),
    ]
